version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpu_app
    ports:
      - "8501:8501"
      - "8502:8502"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app
